apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app135
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app135
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/timwangwmw/tanzu-java-web-app135.git
    # subPath: tanzu-java-web-app135
